project_id = "hewyffhdykietximpfbu"

[functions.confirm-email-subscription]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-team-invite]
verify_jwt = false

[functions.send-team-notification]
verify_jwt = false